### ISSUE TITLE
iOS Compatibility

### ISSUE THREAD

**Issue by HTRamsey** [PX4/ulog_cpp#13]
@bkueng are you familiar with how to handle this issue?
https://github.com/mavlink/qgroundcontrol/actions/runs/10761996544/job/29841807927

**Comment by bkueng** [comment]
Not specifically. Isn't the actual problem that the sysroot is not found?
```
clang: warning: no such sysroot directory: 'iphoneos' [-Wmissing-sysroot]
```

**Comment by HTRamsey** [comment]
Yeah that's probably it, I will try. For some reason I thought you couldn't include <memory> for iOS and had to write in Objective C
