### ISSUE TITLE
Fails with SIGSEGV

### ISSUE THREAD

**Issue by KiselevIlia** [PX4/ulog_cpp#8]
If there is no field like esc_power in the ulog file which it is trying to get from here
https://github.com/PX4/ulog_cpp/blob/main/examples/ulog_data.cpp#L107
`
 std::cout << "esc_power: " << sample["esc"][7]["esc_power"].as<int>() << "\n";
`

Because of this here will be SIGSEGV:
https://github.com/PX4/ulog_cpp/blob/main/ulog_cpp/messages.cpp#L321
`
return operator[](*field);
`

Because there is no check to see if the field exists:
https://github.com/PX4/ulog_cpp/blob/main/ulog_cpp/messages.hpp#L608
`
std::shared_ptr<Field> field(const std::string& name) const { return _fields.at(name); }
`

It returns shared_ptr with NULL of course, and we got SIGSEGV

**Comment by bkueng** [comment]
You're right, there should be extra checks, and throwing `ParsingException` if a field does not exist. Then the example can catch it an print an error. Do you want to create a PR for that?
